# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vipul Ramtekkar
full_name: Vipul Ramtekkar
email: vipul.ramtekkar16@gmail.com
email2: vipul.ramtekkar@iitb.ac.in
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vipulramtekkar.github.io" # the base hostname & protocol for your site
github_username: VipulRamtekkar
linkedin_username: vipulramtekkar
include: ['_pages']

# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
